env:
  browser: true
  commonjs: true
  es2020: true
  node: true
# FUTURE TBD:
# extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  # FUTURE TBD no-trailing-spaces would be covered by adding
  # extends: 'eslint:recommended' entry above
  no-trailing-spaces: error
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  # FUTURE TBD:
  # quotes:
  #   - error
  #   - single
  # semi:
  #   - error
  #   - always
