env:
  browser: true
  commonjs: true
  es2020: true
  node: true
extends: 'plugin:prettier/recommended'

plugins:
  - es5
  - anti-trojan-source
parserOptions:
  ecmaVersion: 11
rules:
  "anti-trojan-source/no-bidi":
    - error
  linebreak-style:
    - error
    - unix
  strict:
    - error
    - global
